services:
  nginx:
    image: nginx
    build: ./srcs/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - net_inc
    volumes:
      - /home/${LOGIN}/data/wordpress:/var/www/html:ro
    restart: unless-stopped
  
  wordpress:
    image: wordpress
    build: ./srcs/wordpress
    depends_on:
      - mariadb
    networks:
      - net_inc
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - /home/${LOGIN}/data/wordpress:/var/www/html
    restart: unless-stopped

  mariadb:
    image: mariadb
    build: ./srcs/mariadb
    networks:
      - net_inc
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - /home/${LOGIN}/data/mysql:/var/lib/mysql
    restart: unless-stopped

networks:
  net_inc:
    driver: bridge
    